require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ScalesController do

  def mock_scale(stubs={})
    @mock_scale ||= mock_model(Scale, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all scales as @scales" do
      Scale.stub(:all) { [mock_scale] }
      get :index
      assigns(:scales).should eq([mock_scale])
    end
  end

  describe "GET show" do
    it "assigns the requested scale as @scale" do
      Scale.stub(:find).with("37") { mock_scale }
      get :show, :id => "37"
      assigns(:scale).should be(mock_scale)
    end
  end

  describe "GET new" do
    it "assigns a new scale as @scale" do
      Scale.stub(:new) { mock_scale }
      get :new
      assigns(:scale).should be(mock_scale)
    end
  end

  describe "GET edit" do
    it "assigns the requested scale as @scale" do
      Scale.stub(:find).with("37") { mock_scale }
      get :edit, :id => "37"
      assigns(:scale).should be(mock_scale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created scale as @scale" do
        Scale.stub(:new).with({'these' => 'params'}) { mock_scale(:save => true) }
        post :create, :scale => {'these' => 'params'}
        assigns(:scale).should be(mock_scale)
      end

      it "redirects to the created scale" do
        Scale.stub(:new) { mock_scale(:save => true) }
        post :create, :scale => {}
        response.should redirect_to(scale_url(mock_scale))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scale as @scale" do
        Scale.stub(:new).with({'these' => 'params'}) { mock_scale(:save => false) }
        post :create, :scale => {'these' => 'params'}
        assigns(:scale).should be(mock_scale)
      end

      it "re-renders the 'new' template" do
        Scale.stub(:new) { mock_scale(:save => false) }
        post :create, :scale => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scale" do
        Scale.stub(:find).with("37") { mock_scale }
        mock_scale.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :scale => {'these' => 'params'}
      end

      it "assigns the requested scale as @scale" do
        Scale.stub(:find) { mock_scale(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:scale).should be(mock_scale)
      end

      it "redirects to the scale" do
        Scale.stub(:find) { mock_scale(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(scale_url(mock_scale))
      end
    end

    describe "with invalid params" do
      it "assigns the scale as @scale" do
        Scale.stub(:find) { mock_scale(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:scale).should be(mock_scale)
      end

      it "re-renders the 'edit' template" do
        Scale.stub(:find) { mock_scale(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scale" do
      Scale.stub(:find).with("37") { mock_scale }
      mock_scale.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the scales list" do
      Scale.stub(:find) { mock_scale }
      delete :destroy, :id => "1"
      response.should redirect_to(scales_url)
    end
  end

end
